import "./bootstrap";
import "./libs/apexcharts/dist/apexcharts.min.js";
import "./libs/jsvectormap/dist/js/jsvectormap.min.js";
import "./libs/jsvectormap/dist/maps/world.js";
import "./libs/jsvectormap/dist/maps/world.js";
import "./libs/jsvectormap/dist/maps/world-merc.js";
import "./tabler.min.js";
import "./demo.min.js";
import "./script.js";
